### ISSUE TITLE
UI TODO

### ISSUE THREAD

**Issue by milooy** [joshua1988/joshua1988.github.io#2]
- [ ] spoqa han sans 적용
- [ ] float button margin 맞추기
- [ ] 로고 해상도 올리기
- header 크기 조정

**Comment by joshua1988** [comment]
- [ ] hi
